bin/osh fails when venv is missing

diff --git a/bin/osh b/bin/osh
--- a/bin/osh
+++ b/bin/osh
@@ -1,13 +1,16 @@
 #!/bin/zsh
 set -eu -o pipefail
 
-base=${0:a:h}/..
-base=${base:a}
+base=${0:a:h:h}
 cd $base
 
-folder=$base/.venv
-path=($folder/bin $path)
-export VIRTUAL_ENV=$folder
+venv=$base/.venv
+if [[ ! -d $venv ]]; then
+    echo "cannot find virtualenv at $venv" >&2
+fi
+
+path=($venv/bin $path)
+export VIRTUAL_ENV=$venv
 export PYTHONPATH=python
 
 python -m osh $@
